### ISSUE TITLE
Error converting ca chain certificiate field to string

### ISSUE THREAD

**Issue by Wiston999** [jetstack/vault-helper#6]
Hi, I'm getting the error "Error converting ca chain certificiate field to string" when using the cert subcommand.

The error seems to be generated at https://github.com/jetstack/vault-helper/blob/aa9e2ff038852bd99805eafe6b62cbac0147ce39/pkg/cert/cert_CSR.go#L130

After investigating and making direct curl requests to vault server I've seen that the ca_chain in vault's response is an array of strings instead of a string and that might be the reason due to the casting to string fails.

This ca_chain as a list behaviour is present in vault 0.7.3 (the version stated in .gitlab-ci.yml) to latest version (0.9.5).
Links to vault docs referencing the response samples:
0.7.3: https://github.com/hashicorp/vault/blob/v0.7.3/website/source/api/secret/pki/index.html.md#sample-response-15
0.9.5: https://github.com/hashicorp/vault/blob/v0.9.5/website/source/api/secret/pki/index.html.md#sample-response-15

**Comment by simonswine** [comment]
Thanks for the report, this is a bug. I will try to add some test and a fix for this.

@Wiston999 feel free to remind me if there is no progress, I probably have forgotten about this :slightly_smiling_face:

**Comment by Wiston999** [comment]
Hi @simonswine , thanks for your answer.
I think that this bug is not reproduced due to the way the helper setup vault. 
I was trying with root and intermediate CA PKI, that must be the cause that vault is returning the ca_chain field and why using the vault-helper setup procedure the bug is not caught at all.

I thought it was relevant to tell you about that to reproduce the bug.

**Comment by simonswine** [comment]
Ok I have just pushed the 0.9.5 code, that should fix that. Pls repoen if there is still a problem
